### ISSUE TITLE
BYPASS / ON confusion ?

### ISSUE THREAD

**Issue by lauguillier** [brummer10/GxSD1.lv2#2]
Hello Hermann,
First of all many thanks for your amazing devs on guitarix and related work !
I'm having fun with your lv2 plugins, used only within guitarix. I feel confused regarding the BYPASS switch on several plugins, which works as a ON/OFF switch (light ON -> effect is applied, thus bypass is actually off, so BYPASS light should be off, and conversely). On the MOD ui, the switch is actually a power switch and the ligth is on when effect is applied. Am I right ?
I quickly fixed the issue in renaming the switch from BYPASS to ON in the plugin/wathevereffect.ttl on the lv2:name line. Looks better to me, light ON is on, effect is applied.
Any thoughs ?
Thanks
Laurent

**Comment by brummer10** [comment]
Hi Laurent

Yes, you are right.
I should really rename this ports to reflect the state properly. 
If you've like, you may send pull requests, that would speed up the fixing and take some work of from me. 

I'm glad you like the plugs and guitarix otherwise. 

regards
hermann

**Comment by brummer10** [comment]
For guitarix I've now bind the lv2:enabled (BYPASS) switch to the guitarix on/off switch and removed it from the UI. So it wouldn't confuse you there any-more.  

regards
hermann

**Comment by lauguillier** [comment]
Hi Hermann,
great news! That's obviously the best way to fix that, for every plugin at once! I'll check (and enjoy) your last commit on guitarix.
Thanks
Laurent

**Comment by lauguillier** [comment]
Hello Hermann,
I tried the new guitarix version regarding the Bypass / On issue. The ui is now OK, Bypass switch is not displayed any more and ON/OFF switch allows effect enable/disable. I think there is a bug in the plugin select window (ctrl-U), the type for bypass is displayed as 'coarse' instead of 'enabled' ...

**Comment by brummer10** [comment]
Hi Laurent 

Yes, it is. I've fixed it locally here already, but forget to commit it to the repository, will do later today. 
regards
hermann

**Comment by brummer10** [comment]
. . . and done. But I've set it to display type Toggle, as I wouldn't implement a new display type for a control we anyway didn't show on the UI. 

regards
hermann

**Comment by lauguillier** [comment]
Nice !
Thanks
Laurent
